name: new_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^27.1.48
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  pdf: ^3.10.0
  printing: ^5.0.0
  csv: ^5.0.2
  excel: ^2.1.0
  file_saver: ^0.2.10
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/icons/
    - lib/assets/logo.png
